/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

plugins {
  id 'com.android.library'
}

android {
  namespace 'com.facebook.shimmer'
  compileSdk 34

  defaultConfig {
    minSdk 21
    targetSdk 34
  }
}

dependencies {
  implementation 'androidx.annotation:annotation:1.9.1'
}
